### ISSUE TITLE
Liberar CORS para acesso externo do aplicativo

### ISSUE THREAD

**Issue by ErickWendel** [artmanager/artmanager-api#1]
XMLHttpRequest cannot load api.artmanager.com.br:3000/autenticacao?data=ZXJpY2stMTIz. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

**Comment by IcaroBichir** [comment]
Isso é questão conf da api ou do server @gustavosk !?
