### ISSUE TITLE
Remoção de pedido

### ISSUE THREAD

**Issue by IcaroBichir** [artmanager/artmanager-api#10]

**Comment by ErickWendel** [comment]
Request URL:http://api.artmanager.com.br/which
Request Method:DELETE
Status Code:200 OK
Remote Address:54.88.51.30:80
Response Headers
view source
Access-Control-Allow-Origin:*
Connection:keep-alive
Content-Length:25
Content-Type:application/json; charset=utf-8
Date:Wed, 15 Jun 2016 03:02:42 GMT
ETag:W/"19-ljRXNnZJvDHKloxdszW07A"
Server:nginx/1.4.6 (Ubuntu)
X-Powered-By:Express
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:no-cache
Connection:keep-alive
Content-Length:9
Content-Type:text/plain;charset=UTF-8
Host:api.artmanager.com.br
Origin:http://localhost:8100
Pragma:no-cache
Referer:http://localhost:8100/
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2767.0 Safari/537.36
x-access-token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwibmFtZSI6ImFydG1hbmFnZXIiLCJwcm9maWxlIjoxLCJpYXQiOjE0NjQ0MjA5MzB9.72kuOCNsP3xcCad3x5fuNYty9dJa-_y00rkpoYWwMP8
Request Payload
view parsed
{"id":49}
